### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by ddke2** [uohefiuhgiufheuoiw/BLANC-DUMPER#16]
does the blank grabber have a rat in it like the builder gui shit

**Comment by ghost** [comment]
@ddke2 no bruh

**Comment by vanta240i** [comment]
> does the blank grabber have a rat in it like the builder gui shit

You are dealing with indian scammers basically. There is no way of telling what is or what isn't in the builder. Although we don't approve of people using the builder in this repo.

**Comment by ghost** [comment]
> > does the blank grabber have a rat in it like the builder gui shit
> 
> You are dealing with indian scammers basically. There is no way of telling what is or what isn't in the builder. Although we don't approve of people using the builder in this repo.

Just see the code
+ Indian scammers r more powerful than 🪆 russina n hackers

**Comment by 0x633A** [comment]
> + Indian scammers r more powerful than 🪆 russina n hackers

retard

**Comment by 5orai** [comment]
> > > does the blank grabber have a rat in it like the builder gui shit
> > 
> > 
> > You are dealing with indian scammers basically. There is no way of telling what is or what isn't in the builder. Although we don't approve of people using the builder in this repo.
> 
> Just see the code
> 
> * Indian scammers r more powerful than 🪆 russina n hackers

thats why it only takes a few lines of code to fuck your grabber 😄

**Comment by 0x633A** [comment]
@aryan5555github How's Birsa Munda Park bhai
