### ISSUE TITLE
Nice virus

### ISSUE THREAD

**Issue by ghost** [uohefiuhgiufheuoiw/BLANC-DUMPER#2]
I ran it on my main pc and instantly regretted it @uohefiuhgiufheuoiw

**Comment by vanta240i** [comment]
Idk if they don't teach you in India what a virus looks like... but reading the code.. it seems to do nothing malicious.

**Comment by ghost** [comment]
> Idk if they don't teach you in India what a virus looks like... but reading the code.. it seems to do nothing malicious.

Dam u

**Comment by ghost** [comment]
> Idk if they don't teach you in India what a virus looks like... but reading the code.. it seems to do nothing malicious.

How did u get MY IP HOW U FIND MY LOCATION SAY OR ELSE














I WILL HDGSHSGSYEGSYWFEHSGUSTSUSTNSHSGSJSHSH

Y
O
U

**Comment by ghost** [comment]
[huge wall of text]
Xhdhdj
D
D
D
D

D
D
D
D
D

D
D
D
D

D
D
D
D
D
D
D

D

[HUGE WALL OF TEXT]

**Comment by applebytez** [comment]
idiot behavior.
