### ISSUE TITLE
U

### ISSUE THREAD

**Issue by ghost** [uohefiuhgiufheuoiw/BLANC-DUMPER#20]
A storm is coming
Tx
U di

**Comment by ghost** [comment]
@applebytez🪆
Say me wat is tis emonji

**Comment by vanta240i** [comment]
aryan ur friend quit... what happens now?!

**Comment by ghost** [comment]
U don't want to know @applebytez

**Comment by ghost** [comment]
* @m1daz and I'm not ur friend

**Comment by vanta240i** [comment]
friend
